name: CI - Terraform & Wazuh Docker Compose

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assessment/terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init (local backend for CI)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate


  
  docker-compose:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assessment/docker
    services:
      docker:
        image: docker:24.0.7-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Generate Wazuh Indexer Certs
        run: |
          mkdir -p ./config/wazuh_indexer_ssl_certs
          if [ -f generate-indexer-certs.yml ]; then
            docker compose -f generate-indexer-certs.yml run --rm generator
          fi


      - name: Docker Compose Up (test)
        run: |
          docker compose up -d
          sleep 10
          docker ps -a
          docker compose ps


      - name: Wait for Wazuh Manager container
        id: wait_manager
        run: |
          for i in {1..10}; do
            MANAGER_ID=$(docker ps --format '{{.ID}} {{.Image}}' | grep 'wazuh/wazuh-manager' | awk '{print $1}')
            if [ -n "$MANAGER_ID" ]; then
              echo "manager_id=$MANAGER_ID" >> $GITHUB_OUTPUT
              exit 0
            fi
            sleep 10
          done
          docker ps -a
          docker logs $(docker ps -aq)
          exit 1



      - name: Healthcheck Wazuh Manager
        run: |
          export USER=wazuh-wui
          export PWD=MyS3cr37P450r.*-
          CERT=./config/wazuh_indexer_ssl_certs/wazuh.manager.pem
          KEY=./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem
          CA=./config/wazuh_indexer_ssl_certs/root-ca.pem
          curl --cert $CERT --key $KEY --cacert $CA -u $USER:$PWD -k -X GET "https://localhost:55000/security/user/authenticate" -H "Content-Type:application/json" -d "{\"username\":\"$USER\",\"password\":\"$PWD\"}"
          TOKEN=$(curl --cert $CERT --key $KEY --cacert $CA -u $USER:$PWD -k -X GET "https://localhost:55000/security/user/authenticate" -H "Content-Type:application/json" -d "{\"username\":\"$USER\",\"password\":\"$PWD\"}" | jq -r .data.token)
          RESPONSE=$(curl --cert $CERT --key $KEY --cacert $CA -k -H "Authorization: Bearer $TOKEN" https://localhost:55000/)
          TITLE=$(echo "$RESPONSE" | jq -r '.data.title')
          if [ "$TITLE" = "Wazuh API REST" ]; then
            echo "Healthcheck passed: Wazuh API REST detected."
          else
            echo "Healthcheck failed: Unexpected API response."
            echo "$RESPONSE"
            exit 1
          fi
      

      - name: Print all container logs on failure
        if: failure()
        run: docker logs $(docker ps -aq)

      - name: Docker Compose Down
        if: always()
        run: docker compose down -v
