name: CI - Terraform & Wazuh Docker Compose

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assessment/terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init (local backend for CI)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate


  
  docker-compose:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assessment/docker
    services:
      docker:
        image: docker:24.0.7-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Generate Wazuh Indexer Certs
        run: |
          mkdir -p ./config/wazuh_indexer_ssl_certs
          if [ -f generate-indexer-certs.yml ]; then
            docker compose -f generate-indexer-certs.yml run --rm generator
          fi

      - name: Docker Compose Up (test)
        run: |
          docker compose up -d
          sleep 60
          docker ps -a
          docker compose ps

      - name: Healthcheck Wazuh Manager
        run: |
          docker exec wazuh.manager curl -f http://localhost:55000

      - name: Healthcheck Wazuh Dashboard
        run: |
          docker exec wazuh.dashboard curl -f http://localhost:5601

      - name: Docker Compose Down
        if: always()
        run: docker compose down -v
